run:
  deadline: 5m
  tests: false

linters:
  enable-all: true
  disable:
  # Deprecated
  - maligned
  - scopelint
  - golint
  - interfacer
  - exhaustivestruct
  # Not avaliable from go v1.18
  - bodyclose
  - contextcheck
  - nilerr
  - noctx
  - rowserrcheck
  - sqlclosecheck
  - structcheck
  - tparallel
  - unparam
  - wastedassign
  # Only Disabled
  - exhaustruct
  - ireturn
  - wrapcheck

linters-settings:
  lll:
    line-length: 120
