version: '3'

services:

  jaeger:
    image: jaegertracing/all-in-one:1.32
    container_name: jaeger

    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411

    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

    networks:
      - global-default

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq

    ports:
      - 5672:5672

  sfpt:
    image: atmoz/sfpt

    ports:
      - 22:22

    volumes:
      - ./.data/sftp:/home/admin/upload

  aws-localstack:
    container_name: aws-localstack
    image: localstack/localstack

    ports:
      - 4566-4572:4566-4572

    environment:
      - EDGE_PORT=4566
      - SERVICES=sqs,s3
      - DATA_DIR=/tmp/localstack/data

    networks:
      - global-default

    volumes:
      - localstack-s3:/tmp/localstack

networks:
  global-default:
    external: true
